### ISSUE TITLE
[Question] Is evil-make-overriding-map purposely avoided?

### ISSUE THREAD

**Issue by dieggsy** [jojojames/evil-collection#48]
Evil-integration does this to some extent, and it seems like the right approach as it avoids re-defining default keys that you want to stay the same, while you can override keys relevant to evil. This might also make some of the code neater and easier to follow IMO.

**Comment by dieggsy** [comment]
For example, I see `evil-dired.el` uses a lot of the same bindings as are default in `dired-mode-map`, so it's not necessarily easy to tell what's new.

**Comment by jojojames** [comment]
I've understood the dired integration in evil-integration to be pretty broken. Don't those overriding maps create duplicate menus? IIRC, I believe so.

I actually think it makes it more confusing than just using evil-define-key everywhere. At least with evil-define-key, you know the precedence order of the keymaps so it's somewhat easy to reason about.

I'd actually like to either request or make a patch to evil-mode to make that integration (evil-integration.el) optional and just port over the good stuff from that file to this project.

Tangentially, I think @noctuid's general library is pretty slick. I wish evil came with something like that directly instead of a separate library.

**Comment by dieggsy** [comment]
@jojojames dired integration seems to work ok for me? but perhaps you're right in that regard, i haven't looked at the internals of `make-overriding-map` that closely. If the internals are simpler, we should probably keep the current system, though it'd still be nice to have comments on what was taken from the default and what was changed or added.

Agreed on making integration optional, and I use and love general.el as well :)

**Comment by jojojames** [comment]
"Pretty broken" was a heavy comment. It doesn't have very good vim integration first and the duplicate menus are a pretty bad experience in my opinion.

**Comment by dieggsy** [comment]
@jojojames what do you mean by "duplicate menus" here?

**Comment by jojojames** [comment]
Last I checked, the menus in the top toolbar (menu) were duplicated.

Maybe it's fixed by now, but I doubt it.

**Comment by dieggsy** [comment]
@jojojames oh, I always run emacs with `(menu-bar-mode -1)` so that doesn't affect me in any way, but it appears you're right.

**Comment by noctuid** [comment]
+1 to not using `make-overriding-map`. I think it is much better for all keybindings to be made explicit, and `make-overriding-map` has extra effects that may not be expected/desired (e.g. if the user or some other package binds a key in `dired-mode-map` when it is an overriding map).

> I'd actually like to either request or make a patch to evil-mode to make that integration (evil-integration.el) optional and just port over the good stuff from that file to this project.

I agree (let's make an issue if there isn't already one). I also think it should be split into parts (or the option be specific only to parts of it). A lot of the configuration in `evil-intergration.el` is perfectly sane and sensible. The use of `make-overriding-map` and changing the intial state just confuses a lot of users though.

> I wish evil came with something like that directly instead of a separate library.

General.el is designed to be usable without evil. Fwiw `evil-define-key` can now completely replace `(define-key evil-<state>-state-map...)`/`evil-global-set-key`.

**Comment by Ambrevar** [comment]
Agreed with not using `make-overriding-map`.

**Comment by dieggsy** [comment]
@noctuid @Ambrevar I think I've come around to agreeing, though do you have any thoughts on at least adding comments throughout to indicate changes/additions to the default maps?

**Comment by dieggsy** [comment]
hmm, I see `evil-proced.el` does this pretty well

**Comment by jojojames** [comment]
I'm not sure if I want to make it a heavier burden on myself to add those types of comments. Creating the binding in the first place is somewhat tedious work already. :)

I think this is something I'd gladly accept as a pull request or if someone contributed a binding with those types of comments already in.

**Comment by dieggsy** [comment]
totally understandable, i may look into it.

btw, just recently got around to _actually_ using `evil-collection`, and I'm quite liking it so far. Thanks for everyone who started and contributes to this.

i'll close this as all my questions have been addressed.

**Comment by jojojames** [comment]
Thanks! Looking forward to your contributions. :)

Hopefully it gets on melpa soon.

**Comment by jojojames** [comment]
> General.el is designed to be usable without evil. Fwiw evil-define-key can now completely replace (define-key evil-<state>-state-map...)/evil-global-set-key.

@noctuid I like the 'api' of general better than evil-define-key but hesitate to use it for key definitions because it's not a 'default'. It'd be awesome if evil just required general and supplied that instead, especially the vim parallel mappings (e.g. something like evil-nnoremap or similar) would be great.

Another big hitch of vim -> emacs + evil transition is figuring out how to bind keys in emacs and I think general makes it much easier than evil-define-key.

**Comment by jojojames** [comment]
> I agree (let's make an issue if there isn't already one). I also think it should be split into parts (or the option be specific only to parts of it). A lot of the configuration in evil-intergration.el is perfectly sane and sensible. The use of make-overriding-map and changing the intial state just confuses a lot of users though.

https://github.com/emacs-evil/evil/issues/992

**Comment by dieggsy** [comment]
>. ...but hesitate to use it for key definitions because it's not a 'default'.

@jojojames what do you mean by this? If you like it better, it could probably be dropped in "under the hood" if the user dosen't want to deal with general at all, since it wraps evil's key definers. That is, if used in the right way, wouldn't it just be a convenient wrapper around the "defaults"?

>  It'd be awesome if evil just required general and supplied that instead, especially the vim parallel mappings (e.g. something like evil-nnoremap or similar) would be great.

Wouldn't this cause a circular dependency?

**Comment by jojojames** [comment]
I like it better but I'm not sure about bringing in additional dependencies (even if it's a fantastic library).

Re: circular dependency

I don't think so.

**Comment by dieggsy** [comment]
Could you elaborate on why? (I mean, I sorta get it, less dependencies -> more stable, maybe - but there don't seem to be that many as is)

**Comment by jojojames** [comment]
It's just the standard set of points on bringing in dependencies or not.

I like the library but then you'd have to depend on its set of abstractions. You might get to a point where you're debugging the abstraction vs your own stuff.

Also, since it's not in evil, there's the question of future maintainability. If we build on top of it and @noctuid gets bored with it or something :), it'd be hard moving forward unless someone wants to volunteer to keep it alive. If it was in evil repository, there'd be more confidence the keybinding code will continue getting maintaind.

Lastly, since it's not in the evil repository, we can't expect everyone to know how to rebind stuff using general, evil-define-key is standard so everyone can read and modify the code.

Lastly#2, bringing in additional dependencies is never free, you have to deal with its load-time, which to me is a big problem in emacs.

**Comment by dieggsy** [comment]
Agreed on the general points

> Lastly, since it's not in the evil repository, we can't expect everyone to know how to rebind stuff using general, evil-define-key is standard so everyone can read and modify the code.

Eh, I think general's binding functions/macros are (for the most part) pretty intuitive, so I'm not sure how much I agree with this. (They're awesome and capable of doing a lot of magic, but if you saw an existing call to a general function, you could probably quite easily figure out what it does)

> Lastly#2, bringing in additional dependencies is never free, you have to deal with its load-time, which to me is a big problem in emacs.

Is it? IMO emacsclient solves this pretty handily, though I'll admit it's not usually something beginners know about or use, which leaves us back at your point :)

**Comment by noctuid** [comment]
I think it would be far too opinionated to include general.el (or even another even more popular or "essential" package where evil was an actual dependency like evil-surround) with evil. I doubt any evil maintainer would be okay with this change even I wanted to push for it.

> I like the 'api' of general better than evil-define-key but hesitate to use it for key definitions because it's not a 'default'. 

What do you mean by this?

> Another big hitch of vim -> emacs + evil transition is figuring out how to bind keys in emacs and I think general makes it much easier than evil-define-key.

I think it's important to understand how keybindings work before using general.el. One goal of general.el is to be as transparent as possible and not hide anything from the user. `general-define-key` is currently built on top of `evil-define-key`. Also `general-def` (which I recommend over `general-define-key`) and `general-evil-define-key` can essentially act as a drop-in replacements for `evil-define-key`. The definers from general.el have extremely similar syntax to `evil-define-key`, and this is intentional.

> If it was in evil repository, there'd be more confidence the keybinding code will continue getting maintaind.

If I ever was no longer able to maintain general, I'm sure that if there were others willing to maintain it, it wouldn't matter whether or not it was in the evil repository.

**Comment by jojojames** [comment]
> I think it would be far too opinionated to include general.el (or even another even more popular or "essential" package where evil was an actual dependency like evil-surround) with evil. I doubt any evil maintainer would be okay with this change even I wanted to push for it.

I think you can make a case for surround not being part of evil since it was originally a plugin on vim anyways. Keybinding wise, evil-define-key never struck the *ease* that the regular nmap/imap keys did in vim.

> What do you mean by this?

I'm wary of pulling additional dependencies is all. If you're asking about API part of it, it's things like a nice wrapper over evil-make-intercept-map so you can get a truly global/high precedence key to use leader for example and the short functions like (nmap).

> If I ever was no longer able to maintain general, I'm sure that if there were others willing to maintain it, it wouldn't matter whether or not it was in the evil repository.

I agree, but there is definitely a bus factor there. :)
