### ISSUE TITLE
Make company-tng-configure-default optional

### ISSUE THREAD

**Issue by dieggsy** [jojojames/evil-collection#51]
This led to some unexpected behavior for me, and I _strongly_ think it should be set according to some option that defaults to `nil`. This seems like a "completion style" setting rather than a "evil integration" one.

**Comment by jojojames** [comment]
tng mirrors ycmd's behavior pretty well (almost 100% in my experience) so I think it's somewhat suitable as a default for someone looking to have a somewhat 'vimmy' experience. If I were to make a bet, I'd say most people coming from Vim struggle with getting their completion experience similar to their vim one.

For 1. (Whether to have a customizable option), I'm fine with that. A PR would be great. :)

For 2. (Changing the default), I'd like to think it's better defaulted to true (the experts that can switch it off will easily find that option but the newbies would have a harder time discovering that option) but dont mind if it's nil by default since I override it with my own stuff anyway.

Open to opinions either way on 2.

**Comment by dieggsy** [comment]
I feel less strongly about defaulting to `nil` after remembering I can just set it with `custom` or before evil-collection loads. Will open a PR soon.
